channels:
- defaults
- apple
- conda-forge
- pytorch-nightly
- pip
dependencies:
- python=3.10
- numpy
- pandas
- scikit-learn
- matplotlib
- seaborn
- opencv
- pillow
- scikit-image
- conda-forge::nb_conda_kernels
- seaborn
- tensorflow  # [not osx]
- pip
- skl2onnx
- onnxruntime
- skl2onnx
- dvc
- pytorch-nightly::pytorch
- torchvision
- lightning
- ipywidgets
- pip:
  - tensorflow-macos  # [osx]
  - tensorflow-metal  # [osx-arm64]
  - tf2onnx
  - dagshub
  - mlflow
- apple::tensorflow-deps  #[osx]
