channels:
- defaults
- apple
- conda-forge
- pytorch
- pip
dependencies:
- python=3.10
- numpy
- pandas
- scikit-learn
- matplotlib
- seaborn
- opencv
- pillow
- scikit-image
- ipykernel
- seaborn
- tensorflow  # [not osx]
- pip
- skl2onnx
- onnxruntime
- skl2onnx
- dvc
- pytorch::pytorch
- pytorch::torchvision
- lightning
- ipywidgets
- nbconvert
- pip:
  - tensorflow-macos  # [osx]
  - tensorflow-metal  # [osx-arm64]
  - tf2onnx
  - dagshub
  - mlflow
  - xgboost
  - jcopml
- apple::tensorflow-deps  # [osx]
